addresses_and_amounts_csv: 'validators.csv'
refund_destination: '0:28861a9d4a9c9766e1129f7323e01ba0c98c33d5414c0036b8194282ff7abc5c'
keys: 'keys.json'
refund_lock_duration_in_seconds: 10000
contractAddress: ''
